### ISSUE TITLE
Game sometimes crashes just before entering the fire puzzle in sewer

### ISSUE THREAD

**Issue by demonz312** [loiste-interactive/infra-issues#327] opened 2016-01-22 22:09 UTC
i don't know why but game crashes once for me here http://i.imgur.com/0fWmISX.jpg

**Comment by CorruptComputer** [comment] 2016-01-23 22:09
I have been able to reproduce this as well, though the cause is unknown to me.

**Comment by sebastiannielsen** [comment] 2016-01-24 13:02
Theres 2 causes for this:
Either its the background music, which starts at this point, or its the graphics intense operation of the natural gas leak that is also starts rendering at this point.

I suspect the latter. Maybe the gas leak could be redone in such a way it does not cause this problem? Eg, some more garbage (caved in roof or barrels) in the way at the far end of the leaking pipe that blocks passage, and a bit shorter "leak" or "flow".

**Comment by aleksijuvani** [comment] 2016-01-29 17:03
Might be the same issue as #383, the game running out of memory.

**Comment by aleksijuvani** [comment] 2016-01-31 13:21
I managed to reproduce the issue. Looks like a failed memory allocation. I'm not sure yet why this is happening. The game was using 3 gigabytes of memory at the time and only tried to allocate 22.1 megabytes more. There still should be plenty of memory available.

**Comment by sebastiannielsen** [comment] 2016-01-31 13:34
Maybe the graphics card driver needs to use some shared memory belongning to the game to be able to render?

A suggestion is to remake the fire puzzle to not have so much fire. Eg, a shorter flame, but more inpassable rubbish and such (lets say some barrels that the roof caved in on so it become a pillar that is too high to jump over) on the opposite end of the pipe so the only path is through the now shorter flame, thus you still have to solve the puzzle.

It could also be the trigger that starts the "funky" music. What are that trigger more triggering? That trigger might be triggering too much at once, maybe that could be divided into smaller actions using multiple triggers that are triggered in sequence as the player moves forward.

**Comment by aleksijuvani** [comment] 2016-04-08 17:31
Closing this as a possible duplicate of #289. Reopen if this still happens after the update is live.

**Closed by aleksijuvani** 2016-04-08 17:31 UTC
Labels: crash, sewer
