### ISSUE TITLE
[feedback] options need to be accessible from ingame

### ISSUE THREAD

**Issue by evilhackman** [loiste-interactive/infra-issues#282] opened 2016-01-17 15:28 UTC
I remember several people already stated this, including me, during Beta.
Yesterday I watched this guy play http://www.twitch.tv/tddaz/v/35855744 He is a real expert for HL2 mods, and Quake, yet had a hard time figuring out what to do in the first map, and it was painful to see how he had no clue which are the keys because he could not look them up!

I really recommend watching him play for 30 mins or so, as you can really learn what is wrong about the game, esp. the beginning of the game.

**Comment by Yuccaa** [comment] 2016-01-17 15:32
Ingame options are on the list of things to be added to the game soonish. Thanks for link to the stream.

**Comment by aleksijuvani** [comment] 2016-01-18 11:13
Closing this one as a duplicate of #16. Please use that issue for all future discussion.

**Closed by aleksijuvani** 2016-01-18 11:13 UTC
Labels: feedback
