### ISSUE TITLE
watertreatment: Appcrash when transitioning to next map

### ISSUE THREAD

**Issue by Sonador** [loiste-interactive/infra-issues#270] opened 2016-01-16 10:34 UTC
Encountering a reproducable appcrash when attempting to exit watertreatment via the underpass.
Have attempted loading earlier saves and continuing, same result.

Have verified file integrity. Have lowered graphics settings.

https://www.youtube.com/watch?v=P14MfOr-oTc

Crash information:
 Problem Event Name:	APPCRASH
  Application Name:	infra.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5691511f
  Fault Module Name:	tier0.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	56915122
  Exception Code:	40000015
  Exception Offset:	0001c3e2
  OS Version:	6.1.7600.2.0.0.256.1
  Locale ID:	1033
  Additional Information 1:	acac
  Additional Information 2:	acace4b1428ce57603087e8c542adecd
  Additional Information 3:	b2c7
  Additional Information 4:	b2c7116d24351787cd0c2d617300f259

**Comment by Oskutin** [comment] 2016-01-16 11:43
The issue seems to be caused by game running out of allocated memory. The level works when loading the level directly from console.

**Comment by Yuccaa** [comment] 2016-01-16 16:29
Fixed in the next update.

**Closed by Yuccaa** 2016-01-16 16:29 UTC
Labels: crash, sewer
