### ISSUE TITLE
This gate can't be closed once opened

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#88] opened 2015-11-03 13:01 UTC
![251110_2015-11-03_00001](https://cloud.githubusercontent.com/assets/3168386/10908375/28ff5872-823a-11e5-967c-496f79e2c10a.png)

**Comment by Oskutin** [comment] 2015-11-07 18:07
Duplicate of #110

**Closed by Oskutin** 2015-11-07 18:07 UTC
Labels: duplicate, gameplay bug, reserve3
