### ISSUE TITLE
reserve1 : boltcutters missing sound

### ISSUE THREAD

**Issue by N-G-Neer** [loiste-interactive/infra-issues#697] opened 2016-08-04 02:37 UTC
When cutting open the chain at the powerplant, the action is missing sound.
![20160804025945_1](https://cloud.githubusercontent.com/assets/15633807/17388542/2bdaa4f2-59fd-11e6-862e-16753a0fe593.jpg)

**Comment by aleksijuvani** [comment] 2016-08-07 20:01
Can't reproduce the issue. Is this happening in the playtest branch? There was an issue with some sounds not being played, but it has been fixed in the next update.

**Closed by aleksijuvani** 2016-08-07 20:01 UTC
Labels: audio bug, reserve1

**Comment by N-G-Neer** [comment] 2016-08-07 21:32
Yep, this happened on the playtest branch.

**Comment by aleksijuvani** [comment] 2016-08-07 21:42
Alright, good to know. Then this is indeed fixed.
