### ISSUE TITLE
tunnel1 : Floodgate B1/B2 wheel does not work when entering from flood door D4

### ISSUE THREAD

**Issue by wyvren2000** [loiste-interactive/infra-issues#886] opened 2016-11-13 21:44 UTC
There is a progression bug that will prevent completion of the tunnel1 level if you complete the levels in a particular way:

- Working: Entering the Floodgate room timed puzzle from the B side(right) flood door.  B1/B2 wheel turns as required and puzzle can be completed

- Broken: Entering the Floodgate room timed puzzle from flood door D4(left). B1/B2 wheel is selectable, however it cannot be turned, therefore the timed puzzle cannot be completed.  Workaround is loading the previous autosave (The one after the bridge puzzle, not the one after door D4) and using flood door D5 to enter from the B side flood door.

May alternatively have something to do with saving before triggering the timed puzzle

**Comment by wyvren2000** [comment] 2016-11-13 23:28
Went back and tried it again, Opening door B1 before entering through doors D4/B2 seems to fix this.

**Comment by aleksijuvani** [comment] 2016-11-18 18:43
This is possibly fixed in the next update. I couldn't reproduce the issue, but we've disabled collisions for these valves. The collisions have been known to cause similar problems on other levels.

**Closed by aleksijuvani** 2016-11-18 18:43 UTC
Labels: gameplay bug, tunnel
