### ISSUE TITLE
tower: Out of Bounds Glitch

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#583] opened 2016-05-28 14:05 UTC
Link to video: https://streamable.com/qcqf

Jumping from the laterally protruding connectors to the others allows you to get down to the ground level without dying. I took some time to explore the gorgeous environment :sunglasses:

**Comment by Yuccaa** [comment] 2016-05-28 14:54
Duplicate of #526

**Closed by Yuccaa** 2016-05-28 14:54 UTC
Labels: duplicate, tower
