### ISSUE TITLE
Fresh water: stair problem

### ISSUE THREAD

**Issue by mpeltomaa** [loiste-interactive/infra-issues#68] opened 2015-11-01 22:01 UTC
Not possible to come down without jumpin.
![stairs](https://cloud.githubusercontent.com/assets/6035374/10871623/d806fc2c-80f4-11e5-9373-c4ef7109554e.jpg)

**Comment by Oskutin** [comment] 2015-11-01 22:02
Duplicate of #53

**Closed** 2015-11-01 22:04 UTC
Labels: duplicate
