### ISSUE TITLE
reserve2: visual bug in water effects

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#268] opened 2016-01-16 10:04 UTC
Some water effects near the dam disappear with the distance.

DAM-SIDE
None:
![2016-01-16_00009](https://cloud.githubusercontent.com/assets/15571788/12371808/8c16f6b4-bc40-11e5-963c-fd4e81c966ca.jpg)
Half:
![2016-01-16_00010](https://cloud.githubusercontent.com/assets/15571788/12371812/925597b0-bc40-11e5-961d-c285ea855751.jpg)
All
![2016-01-16_00011](https://cloud.githubusercontent.com/assets/15571788/12371814/945af1b8-bc40-11e5-9eff-5131359bb0b4.jpg)

DAM-FRONT
Half:
![2016-01-16_00012](https://cloud.githubusercontent.com/assets/15571788/12371822/cda162cc-bc40-11e5-93dc-05c90285ea6c.jpg)
All:
![2016-01-16_00013](https://cloud.githubusercontent.com/assets/15571788/12371823/d27b4df8-bc40-11e5-8715-f4e62696d6c3.jpg)

**Comment by Yuccaa** [comment] 2016-01-27 15:04
Duplicate of #240

**Closed by Yuccaa** 2016-01-27 15:04 UTC
Labels: reserve2, visual bug
