### ISSUE TITLE
Some achievements not triggering.

### ISSUE THREAD

**Issue by Oskutin** [loiste-interactive/infra-issues#271] opened 2016-01-16 15:49 UTC

**Comment by Arcky431** [comment] 2016-01-19 00:52
"Restoring the Flow" achievement doesn't seem to be working properly.

After repairing one of the flow meters, the console prints the following:
*basemodpanel received event Client:CmdKeyValues*

However, unlike the camera spots achievement or the geocaches one, the console is not printing the following:
*basemodpanel received event OnProfileDataSave*

Progress doesn't seem to be tracked at all.

**Comment by aleksijuvani** [comment] 2016-01-20 14:07
Probably a duplicate of #276.

**Closed by aleksijuvani** 2016-01-20 14:07 UTC
Labels: duplicate, gameplay bug
