### ISSUE TITLE
Cistern: Game crashing

### ISSUE THREAD

**Issue by iamaman24287** [loiste-interactive/infra-issues#903] opened 2016-12-25 06:20 UTC
When you take a picture of the asbestos in the cistern level, the game freezes up and then I have to restart my pc. (See pictures)
![infra feedback 2](https://cloud.githubusercontent.com/assets/19513855/21469965/d7c3daba-cac1-11e6-81a6-5e0c5e5f4d0f.png)
![infra feedback 1](https://cloud.githubusercontent.com/assets/19513855/21469966/d7e473ba-cac1-11e6-9bfd-ff1c0c92c736.png)

**Comment by Yuccaa** [comment] 2016-12-25 14:56
I couldn't replicate this. What were the exact conditions leading to the crash? Does this happen every time?

**Comment by iamaman24287** [comment] 2016-12-26 02:01
When take the photo, the game freezes immmediatly and you can't do anything. That's all that happens. Then you have to start task manager or unplug your machine. It happens every time. I tested it 5 or so times and every time it froze up. I hope you understand now.

**Comment by CorruptComputer** [comment] 2016-12-26 13:16
What are your PC specs, and could you upload your save? Also if you haven't you should try to verify your files. https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335

**Comment by iamaman24287** [comment] 2016-12-27 02:55
I have an HP Pavillion 23 and the game usually runs perfect on medium settings. It's specs are:
CPU: Intel i3  4130T@2.9 GHz
RAM: 8GB DDR3
Storage: 1TB SATA
GPU: 1GB AMD Radeon HD 6450A graphics card
I have verified my files and they are fine. It could just be something with my pc or a gameplay bug.

**Comment by iamaman24287** [comment] 2016-12-27 02:57
BTW how do you upload your save file?

**Comment by CorruptComputer** [comment] 2016-12-27 17:23
From https://github.com/loiste-interactive/infra-issues/issues/877#issuecomment-258912186:

> You can find your saved games by right-clicking INFRA on Steam, selecting "Properties", "Local Files" and "Browse Local Files...". The saves are inside the infra/save folder. I only need the sav files.

**Comment by iamaman24287** [comment] 2016-12-29 09:28
Sry I can't. They were overridden when I saved my game an I have just beat part 2. I ignored the bug and kept on going. It was to say there was a bug (Or not) that you could fix.

**Comment by CorruptComputer** [comment] 2016-12-29 17:07
Try starting that level again, and see if it still happens. Also, if you haven't you should check if your video drivers have an update: http://support.amd.com/en-us/download/auto-detect-tool

**Comment by iamaman24287** [comment] 2017-01-19 08:45
Sorry for the delay. I heard you could open levels with console commands. Do you know how to do that. I do know how to start source games with the console but what is the command if you know.

**Comment by Yuccaa** [comment] 2017-01-20 19:21
`map infra_c7_m4_cistern` if you want to load up `cistern`.

**Comment by aleksijuvani** [comment] 2017-01-21 00:12
I have a feeling that this is caused by the camera flash with certain graphics cards. I've had a couple of people send me crash reports regarding this, and they've all been using integrated graphics.

It'd be a huge help if you could do the following and report back:

1. Load up the level with `map infra_c7_m4_cistern`.
2. After the level has loaded, you can type in `sv_cheats 1` to the console and then `noclip` to fly to this spot.
3. Type in `infra_camera_flash 0` to the console. This should disable the camera flash.
4. Try taking multiple photos of this spot from slightly different angles. Maybe 15 for good measure?
5. Type in `infra_camera_flash 1` to the console. This should re-enable the camera flash.
6. Again, try taking multiple photos of this spot. Try to get the camera flash to trigger.

If this is indeed caused by the camera flash, the game should crash at the sixth step, but not before. Please let me know what happens.

If you run out of camera batteries, you can use `give item_d_batteries` to create a pack at your feet.

**Comment by aleksijuvani** [comment] 2017-02-18 10:41
Nevermind. I think this might be the same issue as #924. This should be fixed in the 2.3.3 beta branch.

**Closed by aleksijuvani** 2017-02-18 10:41 UTC
Labels: cistern, crash

**Comment by iamaman24287** [comment] 2017-02-19 01:33
I'm working on it

**Comment by iamaman24287** [comment] 2017-02-19 03:35
Okay I sort of forgot about it but I tested it. Yeah it doesn't crash without flash.

**Comment by aleksijuvani** [comment] 2017-02-19 10:36
Does it crash with the flash?

**Comment by iamaman24287** [comment] 2017-02-20 06:40
No it dosen't. I read issue #924 and how the new version had been released. I checked this out myself with the flash and it does not crash anymore. Thank you for the patch.

**Comment by aleksijuvani** [comment] 2017-02-20 10:10
Alright, cool. Thanks for letting me know.
