### ISSUE TITLE
Funky circuit breaker shadow

### ISSUE THREAD

**Issue by RetroK** [loiste-interactive/infra-issues#160] opened 2015-11-11 23:19 UTC
The shadow that follows the circuit breaker when picked up while holding a bright flashlight acts like a black box that's being held alongside the actual breaker. http://i.imgur.com/fXtu7cH.jpg

**Comment by Oskutin** [comment] 2015-11-11 23:40
Duplicate of #58

**Closed by Oskutin** 2015-11-11 23:40 UTC
Labels: duplicate
