### ISSUE TITLE
tunnel4: in this tunnel it is easy to get stuck

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#116] opened 2015-11-04 19:29 UTC
If you try to slide along the wall you'll easily get stuck in the pipe in the upper-right corner
![2015-11-04_00008](https://cloud.githubusercontent.com/assets/15571788/10949236/2f5124a0-8332-11e5-8e2c-285b8322e4f8.jpg)
Also it's hard to get out from this hole!
![2015-11-04_00012](https://cloud.githubusercontent.com/assets/15571788/10949355/bf2188c2-8332-11e5-9450-309a10578229.jpg)

**Comment by aleksijuvani** [comment] 2015-11-04 19:41
Duplicate of #18, which is fixed in the next update!

**Closed by aleksijuvani** 2015-11-04 19:41 UTC
Labels: duplicate
