### ISSUE TITLE
isle1: You wouldn't want a train to pass these tracks

### ISSUE THREAD

**Issue by Sidewinder53** [loiste-interactive/infra-issues#1019] opened 2017-09-30 11:53 UTC
https://streamable.com/852ny

I know that this bridge is being renovated, but this seems odd 🤔

**Comment by Sidewinder53** [comment] 2017-09-30 12:20
I think this is more like a visual bug..

**Comment by Yuccaa** [comment] 2017-09-30 13:33
Duplicate of #975

**Closed by Yuccaa** 2017-09-30 13:33 UTC
Labels: duplicate
