### ISSUE TITLE
Furnace graphical issue

### ISSUE THREAD

**Issue by Wingedturtle** [loiste-interactive/infra-issues#147] opened 2015-11-07 19:26 UTC
The roof was glitching out and disappearing for me in the beginning furnace room. 
You can see it at about 3:30 here: https://www.youtube.com/watch?v=gD7beudprHg.
Might just be an issue with my machine, not sure, as it only happened once.

**Comment by FireWarp** [comment] 2015-11-07 19:29
Happens to me too, it is an areaportal issue. It seems to happen if you simply walk through the catwalk on the 4th floor. You can fix it by getting out of a trigger multiple and then touching it once more

**Comment by aleksijuvani** [comment] 2015-11-07 19:54
Closing as a duplicate of #70.

**Closed by aleksijuvani** 2015-11-07 19:54 UTC
Labels: duplicate
