### ISSUE TITLE
Game crashes when I leave the watertreatment 

### ISSUE THREAD

**Issue by R-NK** [loiste-interactive/infra-issues#509] opened 2016-03-20 10:46 UTC
the inside of this building
http://i.imgur.com/xtJ7o9Z.jpg
Here
http://i.imgur.com/30x8PXm.jpg

**Comment by CorruptComputer** [comment] 2016-03-20 15:12
Yeah this is a common issue, it is because the game is running out of memory and is actually a bug with the source engine. This has *mostly* been fixed, but in rare cases like yours it still is not. Can you upload your files from here: **C:\ProgramData\Microsoft\Windows\WER\ReportArchive** that look like **AppCrash_infra.exe_(random numbers and letters)**

In my case it looks like this:
![image](https://cloud.githubusercontent.com/assets/5573038/13905118/4250e6fe-ee84-11e5-8039-8a4b32862d92.png)

**Comment by R-NK** [comment] 2016-03-20 15:29
Here.
[AppCrash.zip](https://github.com/loiste-interactive/infra-issues/files/181353/AppCrash.zip)

**Comment by CorruptComputer** [comment] 2016-03-20 15:55
Ok, this does seem to be the same issue as #431

**Comment by CorruptComputer** [comment] 2016-03-20 16:04
It seems to always be tier0.dll that causes the crashes.
````
Sig[0].Name=アプリケーション名
Sig[0].Value=infra.exe
Sig[1].Name=アプリケーションのバージョン
Sig[1].Value=0.0.0.0
Sig[2].Name=アプリケーションのタイムスタンプ
Sig[2].Value=56b602d2
Sig[3].Name=障害モジュールの名前
Sig[3].Value=tier0.dll
Sig[4].Name=障害モジュールのバージョン
Sig[4].Value=0.0.0.0
Sig[5].Name=障害モジュールのタイムスタンプ
Sig[5].Value=56b602d6
Sig[6].Name=例外コード
Sig[6].Value=40000015
Sig[7].Name=例外オフセット
Sig[7].Value=0001c3e2
DynamicSig[1].Name=OS バージョン
DynamicSig[1].Value=10.0.10586.2.0.0.256.48
DynamicSig[2].Name=ロケール ID
DynamicSig[2].Value=1041
DynamicSig[22].Name=追加情報 1
DynamicSig[22].Value=8125
DynamicSig[23].Name=追加情報 2
DynamicSig[23].Value=81252e09c96c5be83737395ee2a72982
DynamicSig[24].Name=追加情報 3
DynamicSig[24].Value=1f3b
DynamicSig[25].Name=追加情報 4
DynamicSig[25].Value=1f3b989fda0ea49fd30118d58e60a589

**Comment by Yuccaa** [comment] 2016-03-20 19:19
Duplicate of #289

**Closed by Yuccaa** 2016-03-20 19:19 UTC
