### ISSUE TITLE
Fresh water: Flashing house

### ISSUE THREAD

**Issue by mpeltomaa** [loiste-interactive/infra-issues#65] opened 2015-11-01 21:38 UTC
See picture, house is there, then its not.. then again it is.
![house](https://cloud.githubusercontent.com/assets/6035374/10871505/a8c09b74-80f1-11e5-8cab-550082d27446.jpg)

**Comment by Oskutin** [comment] 2015-11-01 21:47
Duplicate of #52

**Closed** 2015-11-01 22:04 UTC
Labels: duplicate, watertreatment
