### ISSUE TITLE
tunnel3: anomalous square of texture

### ISSUE THREAD

**Issue by Gheppio** [loiste-interactive/infra-issues#94] opened 2015-11-03 16:31 UTC
![2015-11-03_00017](https://cloud.githubusercontent.com/assets/15571788/10913965/8a7db3ee-8250-11e5-9c0d-ba9d85d04b1b.jpg)
![2015-11-03_00019](https://cloud.githubusercontent.com/assets/15571788/10913973/901ff46a-8250-11e5-8178-c4cf1440881e.jpg)
The place is this
![2015-11-03_00018](https://cloud.githubusercontent.com/assets/15571788/10913988/9b50c2ba-8250-11e5-8ecd-6f51ceae76da.jpg)

**Comment by aleksijuvani** [comment] 2015-11-03 16:47
Duplicate of #92.

**Closed by aleksijuvani** 2015-11-03 16:47 UTC
