### ISSUE TITLE
Metro: Fire-spitting fan does not have a camera target?

### ISSUE THREAD

**Issue by spacek531** [loiste-interactive/infra-issues#897] opened 2016-12-04 01:33 UTC
It seems like it should: leaking steam have camera targets and turn on/off depending on if it's leaking hard.

![](http://images.akamai.steamusercontent.com/ugc/98347452557563586/4F718A3C64B33C8831EFB162C11C1D2F70365EFE/)
![](http://images.akamai.steamusercontent.com/ugc/98347452557563107/ADAD8B208AD970697223386BF29ED0AEAF346826/)

**Comment by sebastiannielsen** [comment] 2016-12-06 05:31
Its not a fan. Its a oil burner. Its expected that it will work like that when detached. Thats also why it says Under Maintenace on the sign.
So its not actually a bug, its intended.

**Comment by spacek531** [comment] 2016-12-07 01:17
One would expect the fuel, power, and control lines to be removed to make it safe while it's under maintenance. Otherwise one accidental button press and the mechanic's head is barbecued.

**Comment by Sidewinder53** [comment] 2016-12-22 21:40
Duplicate of #752
I still think that this should be a photo spot, as most players will identify wild flames in a maintenance room as something that seems not to be in order.

**Comment by Yuccaa** [comment] 2017-01-21 21:58
Added a target. Spacek531 is right, this is a clear hazard even though it's technically working like it should.

**Closed by Yuccaa** 2017-01-21 21:58 UTC
Labels: gameplay bug, metro
