### ISSUE TITLE
Electrical Shorts visible through wall

### ISSUE THREAD

**Issue by RetroK** [loiste-interactive/infra-issues#159] opened 2015-11-11 22:52 UTC
It's difficult to catch on a screenshot, but the shorts occurring in the water on the other side of this wall appear and are audible (audible is believable, visual is not) here: http://i.imgur.com/BKjeG96.jpg

**Comment by Oskutin** [comment] 2015-11-11 23:12
Duplicate of #46

**Closed by Oskutin** 2015-11-11 23:12 UTC
Labels: duplicate
