### ISSUE TITLE
Missing Texture on light

### ISSUE THREAD

**Issue by CorruptComputer** [loiste-interactive/infra-issues#49] opened 2015-11-01 17:23 UTC
![image](https://cloud.githubusercontent.com/assets/5573038/10870214/e40afc54-808a-11e5-90d1-52090df1aa4f.png)

When you go down the stairs in "forgotten world", after the tunnel collapse.

**Comment by aleksijuvani** [comment] 2015-11-01 17:33
Duplicate of #33.

**Closed by aleksijuvani** 2015-11-01 17:33 UTC
Labels: duplicate
