### ISSUE TITLE
This crane puzzle is stupid

### ISSUE THREAD

**Issue by aleksijuvani** [loiste-interactive/infra-issues#122] opened 2015-11-05 11:15 UTC
The crane controls in furnace have 10 separate buttons that can be used. One of them raises the crane, and the others will kill the player. The buttons are not marked in any way (except for color), which doesn't make sense. It's not obvious that it has separate buttons that can be used. I'm sure that most players will think that it's usable as a whole.

This spot is also missing an autosave, requiring the player to turn the power back on. This only further reinforces the thinking that turning on the power is a mistake and the controls are completely broken.

![251110_2015-11-05_00005](https://cloud.githubusercontent.com/assets/3168386/10966818/d4463234-83be-11e5-89ce-1096af3eae6a.png)

(it's also possible to use all of the buttons without dying if you're standing far enough, which is a bug)

**Comment by Oskutin** [comment] 2015-11-05 22:13
I consider this as duplicate of #126

**Closed by Oskutin** 2015-11-05 22:13 UTC
Labels: feedback, furnace, gameplay bug
