### ISSUE TITLE
Main menu & Options translation, alt+tab switching not working, no sounds at all

### ISSUE THREAD

**Issue by mpeltomaa** [loiste-interactive/infra-issues#42] opened 2015-11-01 15:29 UTC
"Back" is translated "TAKAOSA" if game uses Finnish text. This is totally wrong.

When you press Feedback from main menu, it throws to webpage (and leaves game on background). You can't come back to game with alt+tab or clicking from taskbar. Screen goes to blank and thats it.

For now, i am not able to get any sounds from game.

**Comment by Oskutin** [comment] 2015-11-01 15:41
Caused by lack of finnish translation and soundcache. Latter could be fixed by starting the game with "-console" option and typing "snd_rebuildaudiocache".

**Comment by aleksijuvani** [comment] 2015-11-01 15:44
Hey, thanks for letting us know. We're aware of the sound issue. It only seems to happen when Steam has its language set to something else than English. I'll try to get this fixed as soon as possible.

In the meantime, as a workaround you can go through the following steps to get sound working:

1. Right click it on Steam, go to Properties and "Set Launch Options".
2. Type in `-dev`, press "OK" and "Close".
3. Start the game.
4. Once the game is running, press F1 to open the developer console.
5. Type in `snd_rebuildaudiocache` and press enter.
6. After it notifies that the cache has been built, restart the game.
7. Sound should be working at this point.
8. Revert the launch options back to normal.

**Comment by mpeltomaa** [comment] 2015-11-01 15:48
Did snd_rebuildaudiocache. And rebuild was done, screen dropped to black and lower right corner has "loading icon". Game jammed there. Killed task, restart and now i have sound.

**Comment by Gheppio** [comment] 2015-11-01 18:37
I have absolutely no audio too but i can't fix it because F1 doesn't open the console for me; anyway the -dev infos tell me that it can't find yhe audio files in the repository

**Comment by aleksijuvani** [comment] 2015-11-01 19:02
I've fixed the sound issue and the problem with localized text. This should hit Steam later tonight (or sometime tomorrow at the latest).

Not sure what is up with alt-tabbing though. It seems to work fine on my end (in all three modes: fullscreen, borderless and windowed). The Source engine has always been a bit finicky with alt-tabbing though, so I might just put it down to that.

**Comment by aleksijuvani** [comment] 2015-11-02 13:03
Created issue #75 to track the alt-tabbing problem. Closing this one since the sound and localization problems should be fixed in the next update. Let me know if it's still broken after the update has hit Steam.

**Closed by aleksijuvani** 2015-11-02 13:03 UTC
Labels: gamebreaking
