### ISSUE TITLE
Out of memory when transitioning from watertreatment to sewer

### ISSUE THREAD

**Issue by Dogstreet** [loiste-interactive/infra-issues#289] opened 2016-01-17 21:41 UTC
I'm experiencing a crash leaving the sewage treatment works area: 
- I have made the phone call in the office with the large water control panel
- I have left the office building via the 'Exit'
- I walk down a tunnel and a loading screen starts (indicating the change in area)
- The previous view of the tunnel then flashes up briefly and the program crashes to windows. 

P.S. - Really enjoying the game!! :-)

**Comment by Dogstreet** [comment] 2016-01-17 21:46
P.S. I am running the current version on steam (1.0.3)

**Comment by Oskutin** [comment] 2016-01-17 22:03
You may have to restart that chapter from the main menu, to clear any save data from previous levels, which caused the game to run out of memory. 

We will also take look on the level in future to make it less heavy and less likely to crash.

**Comment by Dogstreet** [comment] 2016-01-17 22:14
I've just restarted the chapter (Fresh Water) as a new game from the main menu and run through it quickly - crashes in the same place I'm afraid,

**Comment by Oskutin** [comment] 2016-01-17 22:21
Okay, Mikko will take look on the levels tomorrow when he wakes up. It will take some time compiling the levels, so in meantime you could try to load the level directly from the console: map infra_c5_m2_sewer.

**Comment by Dogstreet** [comment] 2016-01-17 23:01
Thanks for the workaround - I'll give it a go tomorrow.

**Comment by sebastiannielsen** [comment] 2016-01-19 23:58
Still crashing upon exit of water treatment out to sewer via "dead fish tunnel".
Rig:
5930k
32gb ram
GTX980Ti
Intel 750 SSD 1.2TB with 155 GB free.

**Comment by CorruptComputer** [comment] 2016-01-21 02:37
@Oskutin Can confirm that crashes are happening at the transition to this level, and right after getting the keys at the "Remember to return keys!" sign.

**Comment by Oskutin** [comment] 2016-01-21 02:40
Okay, need to look at that map incase there's something still causing it.

**Comment by sebastiannielsen** [comment] 2016-01-21 02:45
A crash at the keys I have never got, and theres no (technical) reason for the game to crash there. I would suggest checking your computer for bad memory with Memtest or some similiar software, because the key pickup values are stored in RAM (eg, how the games remember that you "have" a specific key), and there can be a bad cell just where the key should be stored.

However, the level transistion is a valid case for a crash, and since its a little bit random if it crash there or not, I suspect the developer is near some ceiling for how many objects or whatever that are allowed to be in a map in source engine.

Maybe a idea would be to divide the level at 2 at the flood gates in the middle? So it becomes 3 level, sewer 1 = the computer space with all the alarms and such, sewer 2 = the part north of the flood gates. The "Remember to return keys" and blue card reader should then be part of sewer 2, and sewer 3 is then below the subway (eg the falling floor).
 
The problem is then that many objects still need to be there to keep the realism, but I think you can come up with a solution to have more garbage outside of the house that will precisely cover the windows when looking from sewer 2, to substantionally reduce the number of objects that need to be inside the house and visible through the windows.

**Comment by CorruptComputer** [comment] 2016-01-21 04:27
@sebastiannielsen I didn't crash when I picked up the keys, I crashed right after when you unlock the gate and walk through.

**Comment by sebastiannielsen** [comment] 2016-01-21 05:05
I suspect this is a GPU issue then. Since when you go through that gate, you will arrive at the leaking gas natural pipe, and that is a HEAVY load for your GPU. Check that your GPU cooling is alright and that the GPU can cope with the load.

**Comment by CorruptComputer** [comment] 2016-01-21 05:29
I have an EVGA Geforce 960 ACX2.0+, so the load and the cooling should be more than needed, however I am not able to reproduce this very consistently.

**Comment by CorruptComputer** [comment] 2016-01-23 22:04
I am able to constantly reproduce the crash upon entering the sewer level, which is giving the following crash report: 

    Faulting application name: infra.exe, version: 0.0.0.0, time stamp: 0x569f31eb
    Faulting module name: tier0.dll, version: 0.0.0.0, time stamp: 0x569f31ed
    Exception code: 0x40000015
    Fault offset: 0x0001c3e2
    Faulting process id: 0x230
    Faulting application start time: 0x01d15628d31a50c0
    Faulting application path: E:\Steam\steamapps\common\infra\infra.exe
    Faulting module path: E:\Steam\steamapps\common\infra\bin\tier0.dll
    Report Id: ca360d8b-23fe-4288-954f-1a3df9af25e6

**Comment by sebastiannielsen** [comment] 2016-01-25 13:17
Crash today in the exact same location, mapchange between watertreatment and sewer. (in the tunnel just before hackerden).
The crash happen randomly, so sometimes it load correctly, sometimes not.

**Comment by CorruptComputer** [comment] 2016-01-26 14:40
@Oskutin would it help if I uploaded the save file that I am able to reproduce this crash on?

**Comment by Oskutin** [comment] 2016-01-26 19:01
Not sure, it might be more related to hardware and other sofware running on background (drivers and etc).

**Comment by Oskutin** [comment] 2016-01-26 19:02
Do you have minidump (.mdp) files of the crash?

**Comment by sebastiannielsen** [comment] 2016-01-26 19:07
[infra_assert_20160117065356_2.zip](https://github.com/loiste-interactive/infra-issues/files/105508/infra_assert_20160117065356_2.zip)

Here is a shitload of minidumps. They all belong to the crash that happen between watertreatmeant and sewer.
Note that some dumps do originate from before first patch attempt (where the transistion would lead to a 100% crash) and some dumps do originate from today.
This should make you able to debug the problem more efficiently, since you now both have dump files from before and after the patch, from the very same hardware. (GTX 980 Ti with 32 GB ram and 5930k)

**Comment by CorruptComputer** [comment] 2016-01-26 19:20
I can provide my minidumps as well if it would help, however I am at work right now so it wouldn't be until later tonight.

**Comment by Oskutin** [comment] 2016-01-26 22:17
No problem. Need to get our programmer to chek those.

**Comment by aleksijuvani** [comment] 2016-01-30 10:08
I was able to reproduce the issue when playing all the way here from the beginning of the game. It's caused by the game running out of memory when loading model textures.

The level will probably need to be made smaller by starting `sewer2` earlier.

> I find it strange however that some sort of "memory issue" can arise on a 32 GB computer. 32 GB should be enough to load the whole INFRA PART 1 as one single big map. Maybe its some setting somewhere in the source engine build belongning to infra that is a bit restrictive set, and should be increased (with the disadvantage that INFRA will not run on some lesser computers).

The Source Engine is 32-bit so it can only use up to 4 gigabytes of memory.

**Comment by sebastiannielsen** [comment] 2016-02-02 17:41
Crashed again on the transistion between watertreatment to sewer today when starting fresh from chapter 5 (fresh water) and then completing the watertreatment, and going through the "dead fish tunnel" to hacker's den. The mapchange there crash the game.

Since the map successfully load for a split second before crashing, I think its some on-map-load-trigger that causes it.

Latest MDMP:
[infra_assert_201602 2183455_1.pptx](https://github.com/loiste-interactive/infra-issues/files/114380/infra_assert_201602.2183455_1.pptx)

(change file extension from pptx to mdmp. Its to circumvent the file filter I had to put a fake extension).

**Comment by sebastiannielsen** [comment] 2016-03-27 16:28
Idea how to fix:
Apparently what I have heard, is that the issue is that it does not correctly unload the latest level.

A fix for this would be to add a small map in-between each, eg a simply pitch-dark room that does nothing else than loading the next map.
Eg:
office - r1_loader - reserve1 - r2_loader - reserve2 - r3_loader - reserve3 - t1_loader .... and so on.
And each _loader is then just a pitch dark box containing a next map trigger with a delay of lets say 1 second.

The great thing with this, is that loading the loader will take less than a second since the loader map is extremely small, like 500kB or something, so users would propably not notice theres a loader in-between each map.
And the great this is then that since apparently it fails to unload the latest map, it would mean that the only thing that would be in memory would be a loader map and the current map, thus avoiding the crash.

You could try something like that and see if that work.

**Comment by aleksijuvani** [comment] 2016-04-08 17:29
Fixed. This was caused by models not being unloaded on level changes. This itself wouldn't be a problem—since models barely take up any memory—but it turns out that they were holding references to textures, which then prevented those from being freed.

**Comment by aleksijuvani** [comment] 2016-04-08 18:25
Looks like this caused an another issue. Still needs more investigation.

**Comment by aleksijuvani** [comment] 2016-04-08 19:18
Fixed for reals now.

**Closed by aleksijuvani** 2016-04-08 19:18 UTC
Labels: crash, sewer
